const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const { PDFParse } = require("pdf-parse");
const mammoth = require("mammoth");

const RESUME_UPLOAD_DIR = path.join(
  __dirname,
  "..",
  "..",
  "uploads",
  "resumes",
);

const ensureResumeDirectory = () => {
  fs.mkdirSync(RESUME_UPLOAD_DIR, { recursive: true });
  return RESUME_UPLOAD_DIR;
};

const parseResumeFile = async (filePath, mimeType = "", originalName = "") => {
  const extension = path.extname(originalName || filePath).toLowerCase();
  const buffer = fs.readFileSync(filePath);

  if (mimeType.includes("pdf") || extension === ".pdf") {
    const parser = new PDFParse({ data: buffer });
    try {
      const parsed = await parser.getText();
      return parsed.text || "";
    } finally {
      await parser.destroy();
    }
  }

  if (mimeType.includes("word") || extension === ".docx") {
    const parsed = await mammoth.extractRawText({ buffer });
    return parsed.value || "";
  }

  return buffer.toString("utf8");
};

const writeTextPdf = ({ outputPath, title, lines }) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: "A4" });
    const stream = fs.createWriteStream(outputPath);

    doc.pipe(stream);
    doc.fontSize(18).font("Helvetica-Bold").text(title, { align: "left" });
    doc.moveDown(0.6);
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#4b5563")
      .text(`Generated by prepAi on ${new Date().toLocaleString()}`);
    doc.moveDown(1);
    doc.fillColor("#111827");

    lines.forEach((line) => {
      if (!line.trim()) {
        doc.moveDown(0.5);
        return;
      }

      if (
        /^[A-Z0-9][A-Z0-9\s,&/-]{4,}$/.test(line.trim()) &&
        line.trim().length < 42
      ) {
        doc.font("Helvetica-Bold").fontSize(12).text(line.trim());
        doc.moveDown(0.3);
        doc.font("Helvetica").fontSize(11);
        return;
      }

      doc.fontSize(11).text(line.trim(), { width: 500 });
    });

    doc.end();

    stream.on("finish", () => resolve(outputPath));
    stream.on("error", reject);
  });
};

const buildResumeTextPdf = async ({ text, title = "ATS Optimized Resume" }) => {
  ensureResumeDirectory();
  const safeName = `resume-optimized-${Date.now()}.pdf`;
  const outputPath = path.join(RESUME_UPLOAD_DIR, safeName);
  const lines = [
    ...String(text || "")
      .replace(/\r/g, "")
      .split("\n")
      .map((line) => line.trimEnd()),
  ];

  await writeTextPdf({ outputPath, title, lines });
  return {
    fileName: safeName,
    filePath: outputPath,
    mimeType: "application/pdf",
  };
};

module.exports = {
  ensureResumeDirectory,
  parseResumeFile,
  writeTextPdf,
  buildResumeTextPdf,
  RESUME_UPLOAD_DIR,
};
